import Head from "next/head";

import { DefaultLayout } from "@/layouts";

import { Benefits } from "@/views/benefits";
import { Introduction } from "@/views/introduction";
import { AboutMe } from "@/views/about-me";
import { SocialService } from "@/views/social-service";
import { Articles } from "@/views/articles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Consultoria Lima</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <Introduction />
        <Benefits />
        {/* <AboutMe />
        <SocialService />
        <Articles /> */}
      </DefaultLayout>
    </>
  );
}
